#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = waypaper --random
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypr-waybar
exec-once = aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log

#áudio
exec-once = swayosd-server

#notificação
exec-once = swaync

#clipboard manager
exec-once = cliphist wipe
exec-once = wl-paste --watch cliphist store

exec-once = hypridle
exec-once = nm-applet
exec-once = bluetoothctl scan on
