# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Fix some dragging issues with XWayland
windowrule = no_focus 1, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false

# Ignore maximize requests from apps. You'll probably like this.
$floatSize = size 944 531

windowrule = suppress_event maximize, match:class .*
windowrule = immediate 1, match:content 3
windowrule = float 1, center 1, $floatSize, match:initial_title Steam\ Settings

# turn off blur
windowrule = opaque 1, float 1, size 720 405, keep_aspect_ratio 1, match:initial_title Picture-in-Picture, pin true
windowrule = opaque 1, match:class app.zen_browser.zen #, match:title ^(.*YouTube.*)$

windowrule = float 1, center 1, $floatSize, match:class blueman-manager
windowrule = float 1, center 1, $floatSize, match:class waypaper
windowrule = float 1, center 1, $floatSize, workspace 12, match:class org.pulseaudio.pavucontrol

# explorador de arquivos
windowrule = float 1, center 1, $floatSize, match:initial_title ^(.*Properties.*)$
windowrule = float 1, center 1, $floatSize, match:initial_title ^(Enter name of file to save to….*)$
windowrule = float 1, center 1, $floatSize, match:initial_title ^(File Upload.*)$
#game
$gameWorkspace = workspace 11 silent
windowrule = content game, match:initial_class ^(steam_app_.*)$, $gameWorkspace
windowrule = content game, match:initial_class ^(Minecraft*.*)$, $gameWorkspace
windowrule = content game, match:initial_title ^(Terraria.*)$, $gameWorkspace
windowrule = content game, match:initial_class ^(blackops.*)$, $gameWorkspace

windowrule = float 1, center 1, $floatSize, match:class org.kde.ark
windowrule = float 1, $floatSize, match:title File Operation Progress

layerrule = match:namespace rofi, dim_around on
