###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywresizeactiveords/
$mainMod = SUPER # Sets "Windows" key as main modifier
$secondaryMod = CTRL_L
$anotherMod = ALT_L

source = binds/windows.conf
source = binds/workspaces.conf
source = binds/zoom.conf
source = binds/fnKeys.conf

# Other configs here

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, Q, exec, $terminal --hold nitch
bind = $mainMod, t, exec, $terminal --hold echo $scripts
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,

#custom
bindr = $mainMod, SUPER_L, exec, $menu -show drun
bind = $mainMod, f, fullscreen, 1
bind = SUPER_SHIFT, f, fullscreen, 3 
bind = $mainMod, b, exec, $terminal btop
bind = $mainMod, BACKSPACE, exec, killall $bar || $bar
bind = $mainMod $secondaryMod, p, exec, hyprpicker -a
bind = $mainMod, period, exec, $menu -modi clipboard:$scripts/cliphist-rofi-img.sh -show clipboard -show-icons
bind = ,Print, exec, flameshot gui
bind = $mainMod, n, exec, swaync-client -t -sw
bind = $mainMod $secondaryMod $anotherMod, escape, exec, sleep 1 && hyprctl dispatch dpms off
bind = $mainMod $secondaryMod, g, exec, $scripts/gamemode.sh
bind = $mainMod, a, exec, killall pavucontrol || pavucontrol

# layout
bind = $mainMod SHIFT_L, l, exec, killall rofi || $scripts/changeLayout.sh 
# teste de submap
bind = $mainMod $secondaryMod, v, submap, virtualMachine
submap = virtualMachine

bind = $mainMod, escape, submap, reset

submap = reset
