###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus

# rofi theme and style
$themeDir = "~/.config/rofi/launchers/type-4/style-1.rasi"
$menu = killall rofi || "$HOME/.config/rofi/launcher.sh"
