# configs of scrolling layout

scrolling {
		fullscreen_on_one_column = false
		column_width = 0.5
		focus_fit_method = 1
		follow_focus = true
		follow_min_visible = 0.4
		direction = right
}

unbind = $mainMod $anotherMod, left
unbind = $mainMod $anotherMod, right
unbind = $mainMod $anotherMod, h
unbind = $mainMod $anotherMod, l

binde = $mainMod $anotherMod, left, exec, $msg colresize +0.1
binde = $mainMod $anotherMod, l, exec, $msg colresize +0.1
binde = $mainMod $anotherMod, right, exec, $msg colresize -0.1
binde = $mainMod $anotherMod, h, exec, $msg colresize -0.1

binde = $mainMod, equal, exec, $msg colresize +0.1
binde = $mainMod, minus, exec, $msg colresize -0.1
bind = $mainMod, r, exec, $msg colresize +conf
bind = $mainMod $secondaryMod, f, exec, $msg fit active
bind = $mainMod, w, exec, $msg fit visible
bind = $mainMod $anotherMod, w, exec, $msg fit all
