# configs of dwindle layout
# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    preserve_split = true # You probably want this
	permanent_direction_override = false
}

bind = $mainMod, z, exec, $msg togglesplit
bind = $mainMod, r, exec, $msg swapsplit
bind = $mainMod ALT_L, h, exec, $msg preselect l
bind = $mainMod ALT_L, l, exec, $msg preselect r
bind = $mainMod ALT_L, j, exec, $msg preselect d
bind = $mainMod ALT_L, k, exec, $msg preselect u
